// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzWa7V5Nf7EPjuVJ6Rk810O0RwqT0MB4I',
    appId: '1:653490858374:web:dfd5ea1c4d26803a532407',
    messagingSenderId: '653490858374',
    projectId: 'larvae-classification',
    authDomain: 'larvae-classification.firebaseapp.com',
    storageBucket: 'larvae-classification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXk9HGPaaO_86Il9lZgG4c4am7bgKXGuA',
    appId: '1:653490858374:android:f71f273030d631bd532407',
    messagingSenderId: '653490858374',
    projectId: 'larvae-classification',
    storageBucket: 'larvae-classification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgZR_QbBxhRp5YVexZn4n-gkbd2KCjd6E',
    appId: '1:653490858374:ios:981e62df85953901532407',
    messagingSenderId: '653490858374',
    projectId: 'larvae-classification',
    storageBucket: 'larvae-classification.appspot.com',
    iosBundleId: 'com.example.larvaeClassification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgZR_QbBxhRp5YVexZn4n-gkbd2KCjd6E',
    appId: '1:653490858374:ios:93418d9f531f018b532407',
    messagingSenderId: '653490858374',
    projectId: 'larvae-classification',
    storageBucket: 'larvae-classification.appspot.com',
    iosBundleId: 'com.example.larvaeClassification.RunnerTests',
  );
}
